---
- name: "Reload systemd"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: not ansible_is_chroot

- name: "Restart NetworkManager"
  become: true
  ansible.builtin.systemd:
    name: "NetworkManager"
    enabled: true
    state: "restarted"
  when: not ansible_is_chroot

- name: "Restart systemd-resolved"
  become: true
  ansible.builtin.systemd:
    name: "systemd-resolved"
    enabled: true
    state: "restarted"
  when: not ansible_is_chroot
  failed_when: false
