---
- name: "Reload systemd"
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: not ansible_is_chroot

- name: "Restart network services"
  become: true
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: "started"
  with_items: "{{ network_services }}"
  when: not ansible_is_chroot
