---
- name: "Add nginx APT repository"
  become: true
  ansible.builtin.deb822_repository:
    name: "nginx"
    types: "deb"
    uris: "https://nginx.org/packages/{{ ansible_facts.distribution | lower }}"
    suites: "{{ ansible_facts.distribution_release }}"
    components: "nginx"
    signed_by: "https://nginx.org/keys/nginx_signing.key"
    state: "present"
    install_python_debian: true

- name: "Install nginx"
  become: true
  ansible.builtin.package:
    name: "nginx"
    state: "present"
    update_cache: true
