---
argument_specs:
  main:
    options:
      mount_device:
        type: "str"
        description: "Device to mount (e.g. PARTLABEL=backup)"
        required: true
      mount_point:
        type: "str"
        description: "Mount point for the drive"
        default: "/mnt/backup"
      mount_fstype:
        type: "str"
        description: "Filesystem type of the device"
        default: "ext4"
      mount_options:
        type: "str"
        description: "Mount options for the device"
        default: "defaults,noatime"
