---
argument_specs:
  main:
    short_description: "Configure basic distro hostname"
    description: "Configure basic distro hostname"
    options:
      hostname:
        type: "str"
        description: "The distro linux network hostname to be used"
