---
- name: "Configure /etc/hostname"
  become: true
  ansible.builtin.copy:
    dest: "/etc/hostname"
    mode: "0644"
    content: |
      {{ hostname }}
  when: hostname is defined

- name: "Configure /etc/hosts"
  become: true
  ansible.builtin.copy:
    dest: "/etc/hosts"
    mode: "0644"
    content: |
      127.0.0.1   localhost
      127.0.1.1   {{ hostname }}
  when: hostname is defined
