---
- name: "Dev configure"
  gather_facts: true
  hosts:
    - desktop.local
    - macbook.local
    - laptop.local
  tasks:
    - name: "Common"
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - "locales"
        - "timezone"
        - "font"
        - "bash"
        - "man"
        - "which"
        - "jq"
        - "ag"
        - "libheif"
        - "tmuxinator"
        - "rsync"
        - "gpg"
        - "git"
        - "git-crypt"
        - "zoxide"
        - "dotfiles"
        - "password_store"
        - "wireguard"
        - "vim"
        - "mise"
        - "neomutt"
        - "go"
        - "python"
        - "nodejs"
        - "docker"
        - "podman"
        - "ansible"
        - "alacritty"
        - "btop"
        - "claude"
        - "firefox"
        - "obsidian"
        - "localsend"
        - "microsoft-teams"
        - "gnome-calendar"
        - "gnome-newsflash"
        - "gnome-planify"
        - "gnome-loupe"
        - "gnome-papers"
        - "gnome-disk-utility"
        - "prometheus-node-exporter"

    - name: "Archlinux"
      when: ansible_distribution == 'Archlinux'
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - "yay"
        - "mpv"
        - "hyprland"
        - "zen-browser"
        - "chromium"
        - "gpu_driver"
        - "steam"

    - name: "Ubuntu"
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - "gnome"

- name: "Raspberry Pi configure"
  gather_facts: true
  hosts:
    - rpi5.local
  roles:
    - role: "locales"
    - role: "timezone"
    - role: "bash"
    - role: "man"
    - role: "jq"
    - role: "ag"
    - role: "btop"
    - role: "gpg"
    - role: "git"
    - role: "git-crypt"
    - role: "dotfiles"
    - role: "password_store"
    - role: "vim"
    - role: "wireguard"
    - role: "gateway"
    - role: "nginx"
    - role: "wg_portal"
    - role: "pihole"
    - role: "prometheus"
    - role: "prometheus-node-exporter"
    - role: "grafana"
    - role: "neomutt"
