---
- name: "Archlinux configure"
  gather_facts: true
  hosts:
    - archlinux.local
    - marchlinux.local
  roles:
    - role: "locales"
    - role: "timezone"
    - role: "yay"
    - role: "font"
    - role: "which"
    - role: "bash"
    - role: "alacritty"
    - role: "man"
    - role: "jq"
    - role: "ag"
    - role: "tmuxinator"
    - role: "rsync"
    - role: "gpg"
    - role: "btop"
    - role: "zoxide"
    - role: "git"
    - role: "git-crypt"
    - role: "dotfiles"
    - role: "password_store"
    - role: "wireguard"
    - role: "vim"
    - role: "mise"
    - role: "gnome-calendar"
    - role: "gnome-loupe"
    - role: "gnome-papers"
    - role: "gnome-planify"
    - role: "gradia"
    - role: "mpv"
    - role: "neomutt"
    - role: "go"
    - role: "python"
    - role: "nodejs"
    - role: "docker"
    - role: "podman"
    - role: "ansible"
    - role: "claude"
    - role: "hyprland"
    - role: "firefox"
    - role: "zen-browser"
    - role: "chromium"
    - role: "obsidian"
    - role: "localsend"
    - role: "microsoft-teams"
    - role: "gpu_driver"
    - role: "steam"
    - role: "prometheus-node-exporter"

- name: "Ubuntu configure"
  gather_facts: true
  hosts:
    - ubuntu.local
  roles:
    - role: "locales"
    - role: "timezone"
    - role: "font"
    - role: "bash"
    - role: "man"
    - role: "jq"
    - role: "ag"
    - role: "tmuxinator"
    - role: "rsync"
    - role: "gpg"
    - role: "git"
    - role: "git-crypt"
    - role: "dotfiles"
    - role: "password_store"
    - role: "vim"
    - role: "mise"
    - role: "neomutt"
    - role: "wireguard"
    - role: "go"
    - role: "python"
    - role: "docker"
    - role: "podman"
    - role: "ansible"
    - role: "gnome"
    - role: "gnome-planify"
    - role: "firefox"
    - role: "obsidian"
    - role: "localsend"
    - role: "microsoft-teams"
    - role: "gnome-calendar"
    - role: "prometheus-node-exporter"

- name: "Raspberry Pi configure"
  gather_facts: true
  hosts:
    - rpi5.local
  roles:
    - role: "locales"
    - role: "timezone"
    - role: "bash"
    - role: "man"
    - role: "jq"
    - role: "ag"
    - role: "btop"
    - role: "gpg"
    - role: "git"
    - role: "git-crypt"
    - role: "dotfiles"
    - role: "password_store"
    - role: "vim"
    - role: "wireguard"
    - role: "gateway"
    - role: "nginx"
    - role: "wg_portal"
    - role: "pihole"
    - role: "prometheus"
    - role: "prometheus-node-exporter"
    - role: "grafana"
    - role: "neomutt"
