---
- name: "Proxy configure"
  gather_facts: true
  hosts:
    - proxy.home.arpa
  roles:
    - role: "caddy"
    - role: "cloudflared"
    - role: "alloy"

- name: "Git configure"
  gather_facts: true
  hosts:
    - git.home.arpa
  roles:
    - role: "cgit"
    - role: "backup"
    - role: "alloy"

- name: "Caldav configure"
  gather_facts: true
  hosts:
    - caldav.home.arpa
  roles:
    - role: "radicale"
    - role: "backup"
    - role: "alloy"

- name: "Tailscale configure"
  gather_facts: true
  hosts:
    - tailscale.home.arpa
  roles:
    - role: "tailscale"
    - role: "alloy"

- name: "Logs configure"
  gather_facts: true
  hosts:
    - logs.home.arpa
  roles:
    - role: "loki"
    - role: "alloy"

- name: "Metrics configure"
  gather_facts: true
  hosts:
    - metrics.home.arpa
  roles:
    - role: "prometheus"
    - role: "alloy"

- name: "Monitor configure"
  gather_facts: true
  hosts:
    - monitor.home.arpa
  roles:
    - role: "grafana"
    - role: "alloy"
