---
- name: "Proxy configure"
  gather_facts: true
  hosts:
    - proxy.home.arpa
  roles:
    - role: "caddy"
    - role: "cloudflared"

- name: "Git configure"
  gather_facts: true
  hosts:
    - git.home.arpa
  roles:
    - role: "cgit"
    - role: "backup"
