---
- name: "Proxy configure"
  gather_facts: true
  hosts:
    - proxy.home.arpa
  roles:
    - role: "caddy"
    - role: "cloudflared"

- name: "Git configure"
  gather_facts: true
  hosts:
    - git.home.arpa
  roles:
    - role: "cgit"
    - role: "backup"

- name: "Caldav configure"
  gather_facts: true
  hosts:
    - caldav.home.arpa
  roles:
    - role: "radicale"
    - role: "backup"

- name: "Tailscale configure"
  gather_facts: true
  hosts:
    - tailscale.home.arpa
  roles:
    - role: "tailscale"
