---
- name: Distro bootstrap configure
  gather_facts: true
  hosts:
    - homelab
    - chroot
  roles:
    - role: "network"
      tags: ["required_for_boot"]
    - role: "user"
      tags: ["required_for_boot"]
    - role: "ssh"
      tags: ["required_for_boot"]
    - role: "locales"
    - role: "timezone"
    - role: "settings"

  pre_tasks:
    - name: "Update package cache"
      become: true
      ansible.builtin.package:
        update_cache: true
      tags: ["required_for_boot"]
