---
- name: "Distro bootstrap configure"
  gather_facts: true
  # Password policy is technically not required for boot,
  # But it's quite nice to configure it for boot and therefore
  # enforce the required policies/configurations wanted for the first passwrod change
  tags: ["required_for_boot"]
  hosts: all
  roles:
    - role: "hostname"
    - role: "network"
    - role: "user"
    - role: "ssh"
    - role: "password_policy"
  pre_tasks:
    - name: "Update package cache"
      become: true
      ansible.builtin.package:
        update_cache: true
      async: 60
      poll: 5
      failed_when: false

- name: "Dev machines configure"
  gather_facts: true
  hosts:
    - archlinux.local
    - ubuntu.local
  roles:
    - role: "locales"
    - role: "timezone"
    - role: "wireguard"
    - role: "homebrew"
    - role: "python"
    - role: "go"
    - role: "docker"
    - role: "podman"

- name: "Raspberry Pi configure"
  gather_facts: true
  hosts:
    - rpi5.local
  become: true
  roles:
    - role: "locales"
    - role: "timezone"
    - role: "wireguard"
    - role: "wireguard_gateway"
    - role: "pihole"
