---
- name: "Bootstrap"
  gather_facts: true
  tags: ["required_for_boot"]
  hosts: all
  roles:
    - role: "hostname"
    - role: "network"
    - role: "user"
    - role: "ssh"
    - role: "password_policy"
  pre_tasks:
    - name: "Update package cache"
      become: true
      ansible.builtin.package:
        update_cache: true
      async: 60
      poll: 5
      failed_when: false
      changed_when: false

- name: "Host Configure"
  ansible.builtin.import_playbook: "configure.yml"

- name: "Service Configure"
  ansible.builtin.import_playbook: "service.yml"
