---
font_packages:
  - "ttf-jetbrains-mono-nerd"
  - "ttf-jetbrains-mono"
  - "noto-fonts"
  - "noto-fonts-emoji"

font_google_fonts:
  - url: "https://fonts.gstatic.com/s/ptsans/v18/jizaRExUiTo99u79P0WOxOGMMDQ.ttf"
    dest: "PTSans-Regular.ttf"
  - url: "https://fonts.gstatic.com/s/ptsans/v18/jizYRExUiTo99u79D0eEwMOJIDQA-g.ttf"
    dest: "PTSans-Italic.ttf"
  - url: "https://fonts.gstatic.com/s/ptsans/v18/jizfRExUiTo99u79B_mh4OmnLD0Z4zM.ttf"
    dest: "PTSans-Bold.ttf"
  - url: "https://fonts.gstatic.com/s/ptsans/v18/jizdRExUiTo99u79D0e8fOytKB8c8zMrig.ttf"
    dest: "PTSans-BoldItalic.ttf"

font_presets:
  - src: "/usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf"
    dest: "/etc/fonts/conf.d/10-sub-pixel-rgb.conf"
  - src: "/usr/share/fontconfig/conf.avail/10-hinting-slight.conf"
    dest: "/etc/fonts/conf.d/10-hinting-slight.conf"
  - src: "/usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf"
    dest: "/etc/fonts/conf.d/11-lcdfilter-default.conf"
  - src: "/usr/share/fontconfig/conf.avail/70-no-bitmaps-except-emoji.conf"
    dest: "/etc/fonts/conf.d/70-no-bitmaps-except-emoji.conf"
