---
homelab:
  vars:
    ansible_connection: "{{ 'local' if inventory_hostname == lookup('pipe', 'uname -n') else 'ssh' }}"
  hosts:
    desktop.local:
    macbook.local:
    laptop.local:
    rpi5.local:
    pve.local:

containers:
  vars:
    ansible_connection: ssh
  hosts:
    proxy.home.arpa:
    git.home.arpa:
    tailscale.home.arpa:
    caldav.home.arpa:
    logs.home.arpa:
    metrics.home.arpa:
    monitor.home.arpa:
    subscriptions.home.arpa:
