---
homelab:
  vars:
    ansible_connection: ssh
  hosts:
    desktop.local:
    macbook.local:
    laptop.local:
    rpi5.local:
    pve.local:

containers:
  vars:
    ansible_connection: ssh
  hosts:
    proxy.home.arpa:
    git.home.arpa:
