---
- name: "Add Caddy APT repository"
  become: true
  ansible.builtin.deb822_repository:
    name: "caddy-stable"
    types: "deb"
    uris: "https://dl.cloudsmith.io/public/caddy/stable/deb/debian"
    suites: "any-version"
    components: "main"
    signed_by: "https://dl.cloudsmith.io/public/caddy/stable/gpg.key"
    state: "present"
    install_python_debian: true

- name: "Install caddy"
  become: true
  ansible.builtin.package:
    name: "caddy"
    state: "present"
    update_cache: true
