---
- name: Converge
  hosts: raspberrypi
  gather_facts: true
  vars:
    ansible_become_method: su
    user_groups: ["wheel", "test_group"]
    locales:
      - "en_US.UTF-8 UTF-8"
    timezone: "GMT"
    pihole_interface: "eth0"
    pihole_domain: "pi.hole"
    pihole_totp_secret: "CHANGEME"
    pihole_password: "{{ ('changeme' | hash('sha256') | hash('sha256'))[:64] }}"
    pihole_dhcp_enabled: false
    wireguard_autostart_connection: ""
    gateway_enabled: true
    gateway_local_ipv4_subnet: "10.0.0.0/24"
    grafana_dashboards:
      - id: 1860
        revision: 37
        name: "node-exporter-full"
        datasource_mappings:
          - key: "000000001"
            value: "prometheus"
    vimrc_repo_url: "https://git.sr.ht/~a14m/.vim"
    password_store_repo_url: "https://github.com/octocat/Spoon-Knife"
    firefox_install_browserpass: true
    firefox_install_passff: true
  roles:
    - role: "hostname"
    - role: "network"
    - role: "user"
    - role: "ssh"
    - role: "password_policy"
    - role: "locales"
    - role: "timezone"
    - role: "wireguard"
    - role: "gateway"
    - role: "nginx"
    - role: "wg_portal"
    - role: "pihole"
    - role: "prometheus"
    - role: "grafana"
    - role: "gnome"
    - role: "rsync"
    - role: "gpg"
    - role: "dotfiles"
    - role: "vim"
    - role: "neomutt"
    - role: "password_store"
    - role: "firefox"
