---
- name: "Create nginx vhost configuration for {{ vhost_name }}"
  become: true
  delegate_to: "{{ vhost_proxy_host }}"
  when: vhost_proxy_type == "nginx"
  ansible.builtin.copy:
    content: "{{ vhost_nginx_content }}"
    dest: "/etc/nginx/conf.d/{{ vhost_name }}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: true
    validate: >
      bash -c 'echo "events { worker_connections 64; } http { include %s; }" > /tmp/nginx-vhost.conf;
        nginx -T -c /tmp/nginx-vhost.conf; ec=$?; rm -f /tmp/nginx-vhost.conf; exit $ec'
  notify: "Restart proxy"

- name: "Create caddy vhost configuration for {{ vhost_name }}"
  become: true
  delegate_to: "{{ vhost_proxy_host }}"
  when: vhost_proxy_type == "caddy"
  ansible.builtin.copy:
    content: "{{ vhost_caddy_content }}"
    dest: "/etc/caddy/sites/{{ vhost_name }}.caddy"
    owner: "root"
    group: "caddy"
    mode: "0640"
    backup: true
    validate: "caddy validate --config %s --adapter caddyfile"
  notify: "Restart proxy"
