---
- name: "Proxy configure"
  gather_facts: true
  hosts:
    - proxy.home.arpa
  vars:
    network_ipv4_address: "{{ ansible_facts.default_ipv4.address }}"
  roles:
    - role: "caddy"

- name: "Git configure"
  gather_facts: true
  hosts:
    - git.home.arpa
  vars:
    network_ipv4_address: "{{ ansible_facts.default_ipv4.address }}"
    backup_name: "git"
    backup_repo: "s3:https://example.com/backups"
    backup_access_key_id: "GK_CHANGEME"
    backup_secret_access_key: "CHANGEME"
    cgit_hostname: "git.example.com"
  roles:
    - role: "cgit"
    - role: "backup"
    - role: "alloy"

- name: "Metrics configure"
  gather_facts: true
  hosts:
    - metrics.home.arpa
  vars:
    network_ipv4_address: "{{ ansible_facts.default_ipv4.address }}"
    prometheus_hostname: "metrics.example.com"
    prometheus_node_exporter_targets:
      - "10.0.0.201:9100"
      - "10.0.0.202:9100"
    prometheus_extra_scrape_configs:
      - name: "garage"
        targets:
          - "10.0.0.254:3903"
        metrics_path: "/metrics"
      - name: "caddy"
        targets:
          - "proxy.home.arpa:9091"
        metrics_path: "/metrics"
      - name: "loki"
        targets:
          - "10.0.0.105:3100"
        metrics_path: "/metrics"
  roles:
    - role: "prometheus"
    - role: "alloy"
