---
- name: "Git configure"
  gather_facts: true
  hosts:
    - git.home.arpa
  vars:
    network_ipv4_address: "{{ ansible_facts['default_ipv4']['address'] }}"
    backup_name: "git"
    backup_repo: "s3:https://example.com/backups"
    backup_access_key_id: "GK_CHANGEME"
    backup_secret_access_key: "CHANGEME"
  roles:
    - role: "cgit"
    - role: "backup"
