---
- name: "Proxy configure"
  gather_facts: true
  hosts:
    - proxy.home.arpa
  vars:
    network_ipv4_address: "{{ ansible_facts.default_ipv4.address }}"
  roles:
    - role: "caddy"

- name: "Caldav configure"
  gather_facts: true
  hosts:
    - caldav.home.arpa
  vars:
    network_ipv4_address: "{{ ansible_facts.default_ipv4.address }}"
    radicale_users:
      - name: "test"
        password_hash: "$2y$05$h9PuTgv/bjaDUemm3oLHTeFZ5T0OMFQVFtrSaoVw6mero0kZXT.e2"
      - name: "test2"
        password_hash: "$2y$05$h9PuTgv/bjaDUemm3oLHTeFZ5T0OMFQVFtrSaoVw6mero0kZXT.e2"
    radicale_collections:
      - owner: "test"
        collection: "example"
        members: ["test2"]
    radicale_hostname: "caldav.example.com"
    backup_name: "caldav"
    backup_repo: "s3:https://example.com/backups"
    backup_access_key_id: "GK_CHANGEME"
    backup_secret_access_key: "CHANGEME"
  roles:
    - role: "radicale"
    - role: "backup"
