---
- name: "Set management IP in /etc/hosts for PVE cert generation"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/hosts"
    regexp: "^{{ network_ipv4_address }}"
    line: "{{ network_ipv4_address }}  {{ ansible_facts['hostname'] }}"
    state: present
  notify: "Restart pveproxy"
  tags:
    - "molecule-notest"

- name: "Deploy bridge master connection"
  become: true
  ansible.builtin.template:
    src: "vmbr0.nmconnection.j2"
    dest: "/etc/NetworkManager/system-connections/vmbr0.nmconnection"
    owner: "root"
    group: "root"
    mode: "0600"
  notify: "Restart NetworkManager"

- name: "Override ethernet connection as bridge port"
  become: true
  ansible.builtin.template:
    src: "ethernet.nmconnection.j2"
    dest: "/etc/NetworkManager/system-connections/ethernet.nmconnection"
    owner: "root"
    group: "root"
    mode: "0600"
  notify: "Restart NetworkManager"

- name: "Wait for connection to recover after bridge reconfiguration"
  ansible.builtin.wait_for_connection:
    delay: 5
    timeout: 30
