---
- name: "Check installed python versions"
  ansible.builtin.command:
    cmd: "mise ls python"
  register: python_installed_versions
  changed_when: false
  failed_when: false

- name: "Install python {{ item }}"
  ansible.builtin.command:
    cmd: "mise use --global python@{{ item }}"
  changed_when: true
  when: item not in python_installed_versions.stdout
  loop: "{{ python_versions }}"

- name: "Check installed uv version"
  ansible.builtin.command:
    cmd: "mise ls uv"
  register: python_uv_installed_version
  changed_when: false
  failed_when: false

- name: "Install uv {{ python_uv_version }}"
  ansible.builtin.command:
    cmd: "mise use --global uv@{{ python_uv_version }}"
  changed_when: true
  when: uv_version not in python_uv_installed_version.stdout
