---
- name: "Create backup mount point"
  become: true
  ansible.builtin.file:
    path: "{{ backup_mount_point }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Mount backup drive"
  become: true
  ansible.posix.mount:
    path: "{{ backup_mount_point }}"
    src: "{{ backup_device }}"
    fstype: "{{ backup_fstype }}"
    opts: "{{ backup_mount_options }}"
    state: "mounted"
