---
- name: "Check if sshd is installed ({{ pve_lxc_id }})"
  become: true
  ansible.builtin.command:
    cmd: >
      pct exec {{ pve_lxc_id }} -- sh -c '
      . /etc/os-release;
      case $ID in
        alpine) apk info openssh ;;
        debian|ubuntu) dpkg -l openssh-server ;;
        *) echo "Unsupported distro: $ID" && exit 1 ;;
      esac;'
  register: pve_lxc_ssh_check
  changed_when: false
  failed_when: false
  tags:
    - "molecule-notest"

- name: "Install openssh ({{ pve_lxc_id }})"
  become: true
  tags:
    - "molecule-notest"
  when: pve_lxc_ssh_check.rc != 0
  ansible.builtin.command:
    cmd: >
      pct exec {{ pve_lxc_id }} -- sh -c '
      . /etc/os-release;
      case $ID in
        alpine) apk add --no-cache openssh ;;
        debian|ubuntu) apt-get install -y openssh-server ;;
        *) echo "Unsupported distro: $ID" && exit 1 ;;
      esac;'
  changed_when: true

- name: "Configure openssh ({{ pve_lxc_id }})"
  become: true
  tags:
    - "molecule-notest"
  block:
    - name: "Deploy ssh host private key ({{ pve_lxc_id }})"
      no_log: true
      ansible.builtin.command:
        cmd: >
          pct exec {{ pve_lxc_id }} -- sh -c
          'umask 077; cat > /etc/ssh/ssh_host_ed25519_key'
        stdin: "{{ pve_lxc_ssh_private_key | trim }}\n"
      changed_when: true

    - name: "Deploy ssh host public key ({{ pve_lxc_id }})"
      ansible.builtin.command:
        cmd: >
          pct exec {{ pve_lxc_id }} -- sh -c
          'cat > /etc/ssh/ssh_host_ed25519_key.pub; chmod 0644 /etc/ssh/ssh_host_ed25519_key.pub'
        stdin: "{{ pve_lxc_ssh_public_key | trim }}\n"
      changed_when: true

    - name: "Render sshd_config ({{ pve_lxc_id }})"
      ansible.builtin.template:
        src: "sshd_config.j2"
        dest: "/tmp/sshd_config_{{ pve_lxc_id }}"
        mode: "0600"

    - name: "Push sshd_config into container ({{ pve_lxc_id }})"
      ansible.builtin.command:
        cmd: pct push {{ pve_lxc_id }} /tmp/sshd_config_{{ pve_lxc_id }} /etc/ssh/sshd_config --perms 0640
      changed_when: true

    - name: "Remove temp sshd_config ({{ pve_lxc_id }})"
      ansible.builtin.file:
        path: "/tmp/sshd_config_{{ pve_lxc_id }}"
        state: absent

    - name: "Enable and start sshd ({{ pve_lxc_id }})"
      ansible.builtin.command:
        cmd: >
          pct exec {{ pve_lxc_id }} -- sh -c
          '. /etc/os-release;
          case $ID in
            alpine) rc-update add sshd default; rc-service sshd restart ;;
            debian|ubuntu) systemctl enable --now ssh; systemctl restart ssh ;;
            *) echo "Unsupported distro: $ID" && exit 1 ;;
          esac'
      changed_when: true
