---
wallos_version: "v5.4.5"
wallos_install_dir: "/opt/wallos"
wallos_port: 8282
wallos_main_currency: "EUR"
wallos_language: "de"
wallos_jobs:
  - name: "updatenextpayment"
    script: "updatenextpayment.php"
    cron_schedule: "0 1 * * *"
    systemd_schedule: "*-*-* 01:00:00"
  - name: "updateexchange"
    script: "updateexchange.php"
    cron_schedule: "0 2 * * *"
    systemd_schedule: "*-*-* 02:00:00"
  - name: "sendcancellationnotifications"
    script: "sendcancellationnotifications.php"
    cron_schedule: "0 8 * * *"
    systemd_schedule: "*-*-* 08:00:00"
  - name: "sendnotifications"
    script: "sendnotifications.php"
    cron_schedule: "0 9 * * *"
    systemd_schedule: "*-*-* 09:00:00"
  - name: "sendverificationemails"
    script: "sendverificationemails.php"
    cron_schedule: "*/2 * * * *"
    systemd_schedule: "*:0/2"
  - name: "sendresetpasswordemails"
    script: "sendresetpasswordemails.php"
    cron_schedule: "*/2 * * * *"
    systemd_schedule: "*:0/2"
  - name: "checkforupdates"
    script: "checkforupdates.php"
    cron_schedule: "0 */6 * * *"
    systemd_schedule: "*-*-* 0/6:00:00"
  - name: "storetotalyearlycost"
    script: "storetotalyearlycost.php"
    cron_schedule: "30 1 * * 1"
    systemd_schedule: "Mon *-*-* 01:30:00"
  - name: "cleanupresettokens"
    script: "cleanupresettokens.php"
    cron_schedule: "0 3 * * *"
    systemd_schedule: "*-*-* 03:00:00"
  - name: "generaterecommendations-weekly"
    script: "generaterecommendations.php weekly"
    cron_schedule: "30 3 * * 1"
    systemd_schedule: "Mon *-*-* 03:30:00"
  - name: "generaterecommendations-monthly"
    script: "generaterecommendations.php monthly"
    cron_schedule: "0 4 1 * *"
    systemd_schedule: "*-*-01 04:00:00"
