---
- name: "Ensure microsoft-teams is installed via flathub"
  community.general.flatpak:
    name: "com.github.IsmaelMartinez.teams_for_linux"
    remote: "flathub"
    state: "present"
    method: "user"
