#!/bin/bash

# Ensure bluetooth is unblocked
rfkill unblock bluetooth

# Better UI than rfkill toggle bluetooth
if bluetoothctl show | grep -q "Powered: yes"; then
  bluetoothctl power off
else
  bluetoothctl power on
fi
