---
- name: "Install proxmox-ve"
  become: true
  ansible.builtin.apt:
    name: "proxmox-ve"
    state: "present"
    update_cache: true
  tags:
    # Since proxmox-ve package setups network and configure grub/kernel hooks which doesn't work in containers
    - "molecule-notest"

- name: "Configure Proxmox repos"
  become: true
  when: proxmox_ve_repo == "no-subscription"
  block:
    - name: "Configure no-subscription repos"
      ansible.builtin.apt_repository:
        repo: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
        state: "present"
        filename: "pve-no-subscription"

    - name: "Remove Proxmox enterprise repo"
      become: true
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/pve-enterprise.list"
        state: "absent"

- name: "Set management IP in /etc/hosts for PVE cert generation"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/hosts"
    regexp: "^{{ network_ipv4_address }}"
    line: "{{ network_ipv4_address }}  {{ hostname }}"
    state: present
  notify: "Restart pveproxy"
  tags:
    # Since container doesn't have network ip address, skipping this test
    - "molecule-notest"

- name: "Enable and start Proxmox VE services"
  become: true
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: "started"
  loop:
    - "pve-cluster"
    - "pvedaemon"
    - "pveproxy"
    - "pvestatd"
  tags:
    # Since proxmox-ve package was ignored from testing, we need to ignore this too
    - "molecule-notest"
