---
- name: "Ensure tailscale is installed"
  become: true
  ansible.builtin.package:
    name: "tailscale"
    state: "present"

- name: "Enable and start tailscale"
  become: true
  ansible.builtin.systemd_service:
    name: "tailscaled"
    enabled: true
    state: "started"
