---
dependencies:
  - role: "proxmox-kernel-helper"
galaxy_info:
  author: "a14m"
  description: "Install Proxmox VE on Debian"
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "Debian"
      versions:
        - "bookworm"
