---
- name: "Restart lighttpd"
  become: true
  ansible.builtin.service:
    name: lighttpd
    state: restarted

- name: "Restart proxy"
  become: true
  delegate_to: "proxy.home.arpa"
  ansible.builtin.service:
    name: "{{ hostvars['proxy.home.arpa'].proxy_type }}"
    state: restarted
