---
- name: Converge
  hosts: instance
  vars:
    ansible_become_method: su
    network_wifi_ssid: "TEST_WIFI_SSID"
    network_wifi_pass: "TEST_WIFI_PASS"
    username: test_user
    user_groups: ["wheel", "test_group"]
    ssh_port: 1337
    locales:
      - "en_US.UTF-8 UTF-8"
    settings_timezone: "GMT"
  roles:
    - role: network
    - role: user
    - role: ssh
    - role: locales
    - role: settings
