---
- name: Converge
  hosts: instance
  gather_facts: true
  vars:
    ansible_become_method: su
    network_wifi_ssid: "TEST_WIFI_SSID"
    network_wifi_pass: "TEST_WIFI_PASS"
    username: test_user
    user_public_keys:
      - "ssh-ed25519 AAAA...fMo"
      - "ssh-rsa AAAA...4I3"
    user_groups: ["wheel", "test_group"]
    ssh_port: 1337
    locales:
      - "en_US.UTF-8 UTF-8"
    timezone: "GMT"
    python_global_version: "3.13"
    python_versions:
      - "3.13"
    pihole_interface: "eth0"
    pihole_domain: "pi.hole"
    wireguard_connections:
      protonvpn-example: |
        [Interface]
        PrivateKey = your_private_key_here
        Address = 10.2.0.2/32
        DNS = 10.2.0.1

        [Peer]
        PublicKey = server_public_key
        AllowedIPs = 0.0.0.0/0
        Endpoint = example.protonvpn.com:51820
  roles:
    - role: "network"
    - role: "user"
    - role: "ssh"
    - role: "password_policy"
    - role: "locales"
    - role: "timezone"
    - role: "homebrew"
    - role: "python"
    - role: "wireguard"
    - role: "pihole"
      when:
        - lookup('ansible.builtin.env', 'MOLECULE_DISTRO') == 'ubuntu' or
          lookup('ansible.builtin.env', 'MOLECULE_DISTRO') == 'raspberrypi'
