---
- name: Converge
  hosts: instance
  gather_facts: true
  vars:
    ansible_become_method: su
    network_wifi_ssid: "TEST_WIFI_SSID"
    network_wifi_pass: "TEST_WIFI_PASS"
    username: test_user
    user_groups: ["wheel", "test_group"]
    ssh_port: 1337
    locales:
      - "en_US.UTF-8 UTF-8"
    timezone: "GMT"
  roles:
    - role: network
    - role: user
    - role: ssh
    - role: password_policy
    - role: locales
    - role: timezone
    - role: homebrew
    - role: pihole
      vars:
        pihole_interface: "eth0"
        pihole_domain: "pi.hole"
      when:
        - lookup('ansible.builtin.env', 'MOLECULE_DISTRO') == 'ubuntu' or
          lookup('ansible.builtin.env', 'MOLECULE_DISTRO') == 'raspberrypi'
