---
- name: "Include OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: "Install Intel graphics driver packages"
  become: true
  ansible.builtin.package:
    name: "{{ intel_graphics_packages }}"
    state: "present"
