---
- name: "Add Grafana repository"
  become: true
  ansible.builtin.deb822_repository:
    name: "grafana"
    types: "deb"
    uris: "https://apt.grafana.com"
    suites: "stable"
    components: "main"
    signed_by: "https://apt.grafana.com/gpg.key"
    state: "present"
    install_python_debian: true

- name: "Update package cache"
  become: true
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: "Install loki"
  become: true
  ansible.builtin.package:
    name: "loki"
    state: "present"
