---
- name: "Add edge community repository for loki"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/apk/repositories"
    line: "@edge http://dl-cdn.alpinelinux.org/alpine/edge/community"
    state: "present"

- name: "Update apk package cache"
  become: true
  community.general.apk:
    update_cache: true
  changed_when: false

- name: "Install loki"
  become: true
  ansible.builtin.package:
    name:
      - "loki@edge"
      - "loki-openrc@edge"
    state: "present"
