---
- name: "Create loki group"
  become: true
  ansible.builtin.group:
    name: "loki"
    system: true

- name: "Create loki user"
  become: true
  ansible.builtin.user:
    name: "loki"
    group: "loki"
    system: true
    shell: "/sbin/nologin"
    create_home: false

- name: "Include OS-specific installation tasks"
  ansible.builtin.include_tasks: "install-{{ ansible_facts.os_family | lower }}.yml"

- name: "Create loki directories"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    owner: "loki"
    group: "loki"
    mode: "0750"
  loop:
    - "/etc/loki"
    - "/var/lib/loki"

- name: "Configure loki service (conf.d overrides)"
  become: true
  ansible.builtin.template:
    src: "loki.confd.j2"
    dest: "/etc/conf.d/loki"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Restart loki"

- name: "Create loki configuration"
  become: true
  ansible.builtin.template:
    src: "loki.yml.j2"
    dest: "/etc/loki/config.yml"
    owner: "loki"
    group: "loki"
    mode: "0640"
  notify: "Restart loki"

- name: "Start and enable loki"
  become: true
  ansible.builtin.service:
    name: "loki"
    state: "started"
    enabled: true
