---
- name: "Restart NetworkManager"
  become: true
  ansible.builtin.systemd_service:
    name: "NetworkManager"
    state: "restarted"
  async: 10
  poll: 0

- name: "Restart pveproxy"
  become: true
  ansible.builtin.systemd_service:
    name: "pveproxy"
    state: "restarted"
  tags:
    - "molecule-notest"
