---
- name: "Reload systemd"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: not ansible_is_chroot

- name: "Restart ssh"
  become: true
  ansible.builtin.systemd:
    name: "{{ ssh_service_name }}"
    state: "restarted"
  when: not ansible_is_chroot
