---
- name: "Check if gum is installed"
  ansible.builtin.command:
    cmd: "mise ls gum"
  register: gum_installed
  changed_when: false

- name: "Install gum"
  ansible.builtin.command:
    cmd: "mise use --global gum@latest"
  changed_when: true
  when: gum_installed.stdout == ''
