---
- name: "Check installed go version"
  ansible.builtin.command:
    cmd: "mise current go"
  register: go_current_version
  changed_when: false
  failed_when: false

- name: "Install go {{ go_version }}"
  ansible.builtin.command:
    cmd: "mise use --global go@{{ go_version }}"
  changed_when: true
  when: go_version not in go_current_version.stdout

- name: "Add Go bin to shell profile"
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.bashrc"
    state: "present"
    prepend_newline: true
    append_newline: true
    marker: "# ==== {mark} ANSIBLE GO CONFIG"
    block: |
      if [ -d "$HOME/go/bin" ]; then
        export PATH="$HOME/go/bin:$PATH"
      fi
