---
- name: "Validate version format"
  ansible.builtin.assert:
    that:
      - ansible_core_version | regex_search('^[0-9]+\\.[0-9]+\\.[0-9]+$') is not none
      - molecule_version | regex_search('^[0-9]+\\.[0-9]+\\.[0-9]+$') is not none
    msg: "Version must be in major.minor.patch format"

- name: "Install ansible core"
  ansible.builtin.command:
    cmd: "uv tool install ansible-core=={{ ansible_core_version }}"
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/ansible-core"
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"

- name: "Install molecule"
  ansible.builtin.command:
    cmd: "uv tool install molecule=={{ molecule_version }} --with 'molecule-plugins[docker,podman]'"
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/molecule"
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
