---
- name: "Reload sysctl"
  become: true
  ansible.builtin.command:
    cmd: "sysctl -p"
  changed_when: false

- name: "Reload systemd"
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "Reload udev"
  become: true
  ansible.builtin.command:
    cmd: "udevadm control --reload-rules"
  changed_when: false
