---
- name: "Ensure sudo is installed"
  become: true
  ansible.builtin.package:
    name:
      - "sudo"
    state: "present"

- name: "Configure permissions for group: sudo"
  become: true
  community.general.sudoers:
    name: "sudo"
    group: "sudo"
    commands: "ALL"
    nopassword: false
    sudoers_path: "/etc/sudoers.d"
    state: present
