---
- name: "Include OS-specific installation tasks"
  ansible.builtin.include_tasks: "install-{{ ansible_facts.os_family | lower }}.yml"

- name: "Create git group"
  become: true
  ansible.builtin.group:
    name: "{{ cgit_ssh_user }}"
    system: true

- name: "Create git user"
  become: true
  ansible.builtin.user:
    name: "{{ cgit_ssh_user }}"
    group: "{{ cgit_ssh_user }}"
    shell: "/usr/bin/git-shell"
    create_home: true
    system: true
    password: "*"

- name: "Set default branch name for new repos"
  become: true
  community.general.git_config:
    name: init.defaultBranch
    scope: system
    value: main

- name: "Deploy authorized_keys"
  become: true
  ansible.posix.authorized_key:
    user: "{{ cgit_ssh_user }}"
    key: "{{ item }}"
    state: present
  loop: "{{ user_public_keys }}"

- name: "Create repos directory"
  become: true
  ansible.builtin.file:
    path: "{{ cgit_repos_dir }}"
    state: directory
    owner: "{{ cgit_ssh_user }}"
    group: "{{ cgit_ssh_user }}"
    mode: "2755"

- name: "Create git template hooks directory"
  become: true
  ansible.builtin.file:
    path: "{{ cgit_repos_dir }}/.git-templates/hooks"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Deploy post-receive hook to git template"
  become: true
  ansible.builtin.copy:
    src: "post-receive"
    dest: "{{ cgit_repos_dir }}/.git-templates/hooks/post-receive"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Set git template dir for new repos"
  become: true
  community.general.git_config:
    name: init.templateDir
    scope: system
    value: "{{ cgit_repos_dir }}/.git-templates"

- name: "Deploy cgitrc"
  become: true
  ansible.builtin.template:
    src: "cgitrc.j2"
    dest: "/etc/cgitrc"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Deploy lighttpd config"
  become: true
  ansible.builtin.template:
    src: "cgit.lighttpd.conf.j2"
    dest: "/etc/lighttpd/lighttpd.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Restart lighttpd"

# TODO: Remove this when cgit is released with dark mode support (development branch)
- name: "Deploy dark-mode cgit.css"
  become: true
  ansible.builtin.copy:
    src: "cgit.css"
    dest: "/usr/share/webapps/cgit/cgit.css"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Enable and start services"
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - "lighttpd"
    - "{{ 'ssh' if ansible_facts.os_family == 'Debian' else 'sshd' }}"

- name: "Create cgit proxy vhost"
  when: cgit_hostname is defined
  ansible.builtin.include_role:
    name: "vhost"
  vars:
    vhost_name: "cgit"
    vhost_nginx_content: "{{ lookup('template', 'cgit.nginx.conf.j2') }}"
    vhost_caddy_content: "{{ lookup('template', 'cgit.caddy.j2') }}"
