---
argument_specs:
  main:
    options:
      hostname:
        type: "str"
        description: "The distro linux network hostname to be used"
      network_wifi_ssid:
        type: "str"
        description: "The WIFI SSID to be configure when provided"
        required: false
        default: ""
      network_wifi_pass:
        type: "str"
        description: "The WIFI Passphrase to be configure when provided"
        required: false
        default: ""
      network_packages:
        type: "list"
        description: "The network packages to install"
        elements: "str"
      network_packages_removed:
        type: "list"
        description: "The network packages to remove"
        elements: "str"
      network_services:
        type: "list"
        description: "The network services to enable"
        elements: "str"
