---
argument_specs:
  main:
    options:
      wg_portal_version:
        description: "Version of wg-portal to install"
        type: "str"
        default: "latest"
      wg_portal_port:
        description: "Port for wg-portal web interface"
        type: "str"
        default: "8080"
      wg_portal_password:
        description: "Password hash for wg-portal authentication"
        type: "str"
        default: "{{ ('changeme' | hash('sha256') | hash('sha256'))[:64] }}"
      wg_portal_hostname:
        type: "str"
        description: "FQDN for the wg-portal nginx vhost (e.g. 'vpn.home.arpa')."
        default: "vpn.home.arpa"
