FROM docker.io/library/archlinux

ENV container docker

RUN pacman -Syu --noconfirm --needed python3 systemd udev dbus \
    && pacman -Scc --noconfirm

# Workaround archlinux not including any non-indo-european locales
# https://gitlab.archlinux.org/archlinux/archlinux-docker/-/issues/59
RUN cp -r /usr/share/i18n/locales/en_US /usr/share/i18n/locales/de_DE;

VOLUME ["/sys/fs/cgroup"]

CMD ["/lib/systemd/systemd"]
