---
- name: "Proxy configure"
  gather_facts: true
  hosts:
    - proxy.home.arpa
  vars:
    network_ipv4_address: "{{ ansible_facts.default_ipv4.address }}"
  roles:
    - role: "caddy"

- name: "Metrics configure"
  gather_facts: true
  hosts:
    - metrics.home.arpa
  vars:
    network_ipv4_address: "{{ ansible_facts.default_ipv4.address }}"
  roles:
    - role: "prometheus"
    - role: "alloy"
