---
- name: "Ensure timezone package is installed"
  become: true
  ansible.builtin.package:
    name: "tzdata"
    state: "present"

- name: "Link localtime"
  become: true
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: "/etc/localtime"
    state: "link"

- name: "Update timezone"
  become: true
  community.general.timezone:
    name: "{{ timezone }}"
