---
- name: "Include OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: "Install Docker"
  become: true
  ansible.builtin.package:
    name: "{{ docker_package }}"
    state: "present"

- name: "Enable and start Docker service"
  become: true
  ansible.builtin.systemd:
    name: "{{ docker_service }}"
    enabled: true
    state: "started"

- name: "Add user to docker group"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "docker"
    append: true
