---
- name: "Install Docker"
  become: true
  ansible.builtin.package:
    name: "docker"
    state: "present"

- name: "Enable and start Docker service"
  become: true
  ansible.builtin.systemd:
    name: "docker"
    enabled: true
    state: "started"

- name: "Add user to docker group"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "docker"
    append: true
