---
argument_specs:
  main:
    options:
      loki_port:
        type: "int"
        description: "Port for the Loki HTTP API"
        default: 3100
      loki_retention:
        type: "str"
        description: "Log retention period (default 1 month)."
        default: "744h"
