---
- name: "Bootstrap"
  hosts: "ubuntu"
  gather_facts: true
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  vars:
    ansible_become_method: su
    user_public_keys:
      - "ssh-ed25519 AAAA...fMo"
      - "ssh-rsa AAAA...4I3"
    user_groups: ["wheel", "test_group"]
  roles:
    - role: "hostname"
    - role: "network"
    - role: "user"
    - role: "ssh"
    - role: "password_policy"
  tasks:
    - name: "Configure passwordless sudo for testing"
      ansible.builtin.copy:
        content: "%test_group ALL=(ALL) NOPASSWD: ALL\n"
        dest: "/etc/sudoers.d/test_group"
        mode: "0440"
        validate: 'visudo -cf %s'

- name: "Configure"
  hosts: "ubuntu"
  gather_facts: true
  remote_user: "{{ username }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  vars:
    ansible_become_method: sudo
    ansible_is_chroot: false
    locales:
      - "en_US.UTF-8 UTF-8"
    timezone: "GMT"
    wireguard_autostart_connection: ""
    gateway_enabled: false
    gateway_local_ipv4_subnet: "10.0.0.0/24"
    python_global_version: "3.13"
    python_versions:
      - "3.13"
    vimrc_repo_url: "https://git.sr.ht/~a14m/.vim"
    password_store_repo_url: "https://github.com/octocat/Spoon-Knife"
    firefox_install_browserpass: true
    firefox_install_passff: true
  roles:
    - role: "locales"
    - role: "timezone"
    - role: "bash"
    - role: "man"
    - role: "jq"
    - role: "ag"
    - role: "tmux"
    - role: "wireguard"
    - role: "gateway"
    - role: "python"
    - role: "go"
    - role: "rust"
    - role: "docker"
    - role: "podman"
    - role: "ansible"
    - role: "nginx"
    - role: "prometheus"
    - role: "grafana"
    - role: "gnome"
    - role: "rsync"
    - role: "gpg"
    - role: "dotfiles"
    - role: "vim"
    - role: "neomutt"
    - role: "password_store"
    - role: "which"
    - role: "firefox"
    - role: "font"
    - role: "alacritty"
    - role: "btop"
    - role: "wlctl"
    - role: "pipewire"
