---
dependencies: []
galaxy_info:
  author: "a14m"
  description: "Prometheus blackbox exporter for ICMP/DNS/HTTP probing"
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "Debian"
      versions:
        - "bookworm"
    - name: "Ubuntu"
      versions:
        - "noble"
