---
- name: Converge
  hosts: debian
  gather_facts: true
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  vars:
    ansible_become_method: su
    user_public_keys:
      - "ssh-ed25519 AAAA...fMo"
      - "ssh-rsa AAAA...4I3"
    user_groups: ["wheel", "test_group"]
    locales:
      - "en_US.UTF-8 UTF-8"
    timezone: "GMT"
    wireguard_autostart_connection: ""
    gateway_enabled: false
    gateway_local_ipv4_subnet: "10.0.0.0/24"
    python_global_version: "3.13"
    python_versions:
      - "3.13"
    prometheus_host: "localhost"
    prometheus_port: 9090
    prometheus_node_exporter_port: 9100
    grafana_port: 3000
    grafana_dashboards:
      - id: 1860
        revision: 37
        name: "node-exporter-full"
        datasource_mappings:
          - key: "000000001"
            value: "prometheus"
  roles:
    - role: "hostname"
    - role: "network"
    - role: "user"
    - role: "ssh"
    - role: "password_policy"
    - role: "locales"
    - role: "timezone"
    - role: "wireguard"
    - role: "gateway"
    - role: "python"
    - role: "go"
    - role: "docker"
    - role: "podman"
    - role: "ansible"
    - role: "nginx"
    - role: "prometheus"
    - role: "grafana"
    - role: "gnome"
    - role: "rsync"
    - role: "gpg"
