---
backup_name: "backup"
backup_systemd_schedule: "daily"
backup_cron_schedule: "0 0 * * *"
backup_retention_daily: 7
backup_retention_weekly: 4
backup_retention_monthly: 6
backup_s3_region: ""
backup_user: "backup"
backup_group: "backup"
backup_restore_id: "latest"
