---
# Timezone
settings_timezone: "CET"

# Password policy
# https://linux.die.net/man/8/pam_pwquality
settings_pw_policy_enabled: true
settings_pw_policy_difok: 0
settings_pw_policy_minlen: 8
settings_pw_policy_dcredit: 0
settings_pw_policy_ucredit: 0
settings_pw_policy_ocredit: 0
settings_pw_policy_lcredit: 0
settings_pw_policy_minclass: 0
settings_pw_policy_maxrepeat: 0
settings_pw_policy_maxclassrepeat: 0
settings_pw_policy_gecoscheck: 0
