---
pihole_password: "{{ ('changeme' | hash('sha256') | hash('sha256'))[:64] }}"
pihole_totp_secret: "CHANGEME"
pihole_dns:
  - "9.9.9.9"   # Quad9
  - "1.1.1.1"   # Cloudflare
  - "8.8.8.8"   # Google
pihole_interface: "{{ ansible_default_ipv4.interface }}"
pihole_dns_blocking_enabled: true
pihole_dhcp_enabled: false
pihole_dhcp_start: "{{ ansible_default_ipv4.network | regex_replace('\\.0$', '.100') }}"
pihole_dhcp_end: "{{ ansible_default_ipv4.network | regex_replace('\\.0$', '.199') }}"
pihole_dhcp_router: "{{ ansible_default_ipv4.address }}"
pihole_dhcp_lease_time: 24
pihole_dhcp_domain: "local"
pihole_domain: ""
