FROM docker.io/library/debian:13-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends systemd python3 ca-certificates iproute2 \
    && rm -rf /var/lib/apt/lists/*

CMD ["/lib/systemd/systemd"]
