---
argument_specs:
  main:
    short_description: "Install homebrew package manager on Linux distributions"
    description: "Install homebrew package manager on Linux distributions"
    options: {}
