---
dependencies:
  - role: "network"
  - role: "pve"
galaxy_info:
  author: "a14m"
  description: "Configure vmbr0 bridge on Proxmox VE via NetworkManager"
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "Debian"
      versions:
        - "bookworm"
