---
prometheus_host: "localhost"
prometheus_port: 9090
prometheus_retention: "15d"
prometheus_scrape_interval: "15s"

prometheus_targets:
  - "{{ prometheus_host }}:{{ prometheus_port }}"

prometheus_node_exporter_targets: []
