---
- name: "Create wg-portal group"
  become: true
  ansible.builtin.group:
    name: "wg-portal"
    system: true

- name: "Create wg-portal user"
  become: true
  ansible.builtin.user:
    name: "wg-portal"
    group: "wg-portal"
    system: true
    shell: "/usr/sbin/nologin"
    create_home: false

- name: "Check if wg-portal is already installed"
  become: true
  ansible.builtin.stat:
    path: "/etc/wg-portal/wg-portal"
  register: wg_portal_binary_check

- name: "Create wg-portal directories"
  become: true
  ansible.builtin.file:
    path: "/etc/wg-portal"
    state: "directory"
    owner: "root"
    group: "wg-portal"
    mode: "0750"

- name: "Install wg-portal"
  become: true
  when: not wg_portal_binary_check.stat.exists
  block:
    - name: "Download wg-portal installer"
      ansible.builtin.get_url:
        url: "https://git.sr.ht/~a14m/wg-portal/blob/main/deployment/install.sh"
        dest: "/tmp/install_wg-portal.sh"
        mode: "0755"

    - name: "Run wg-portal installer"
      ansible.builtin.command:
        cmd: "/tmp/install_wg-portal.sh {{ wg_portal_version }}"
      args:
        creates: "/etc/wg-portal/wg-portal"

- name: "Set ACL for wg-portal group on /etc/wireguard"
  become: true
  ansible.posix.acl:
    path: "/etc/wireguard"
    entity: "wg-portal"
    etype: "group"
    permissions: "rx"
    recursive: true
    state: "present"

- name: "Set ACL mask for /etc/wireguard"
  become: true
  ansible.posix.acl:
    path: "/etc/wireguard"
    etype: "mask"
    permissions: "rx"
    recursive: true
    state: "present"

- name: "Create wg-portal sudoers file"
  become: true
  ansible.builtin.copy:
    content: |
      %wg-portal ALL=(ALL) NOPASSWD: /usr/bin/wg-quick up *, /usr/bin/wg-quick down *
      %wg-portal ALL=(ALL) NOPASSWD: /usr/bin/wg show
    dest: "/etc/sudoers.d/wg-portal"
    mode: "0440"
    validate: "visudo -cf %s"

- name: "Create wg-portal configuration file"
  become: true
  ansible.builtin.template:
    src: "config.yml.j2"
    dest: "/etc/wg-portal/config.yml"
    owner: "root"
    group: "wg-portal"
    mode: "0640"
  notify: "Restart wg-portal"

- name: "Create wg-portal nginx configurations"
  become: true
  when: wg_portal_by_nginx is defined and wg_portal_by_nginx != ""
  ansible.builtin.copy:
    content: |
      location / {
        proxy_pass http://127.0.0.1:{{ wg_portal_port }}/;
      }
      location /api/connections {
        proxy_pass http://127.0.0.1:{{ wg_portal_port }}/api/connections;
      }
      location /api/status {
        proxy_pass http://127.0.0.1:{{ wg_portal_port }}/api/status;
      }
    dest: "/etc/nginx/conf.d/wg-portal.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: true
    # workaround issue: https://github.com/ansible/ansible/issues/9112
    # ref: https://serverfault.com/a/811520
    validate: >
      bash -c 'echo "events { worker_connections 2; } http { server { include %s; } }" > /tmp/nginx.conf;
        sudo nginx -T -c /tmp/nginx.conf; ec=$?; rm -f /tmp/nginx.conf; exit $ec'
  notify: "Restart nginx"
