---
- name: "Include OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: "Ensure settings packages are installed"
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "{{ settings_pw_quality }}"

- name: "Configure archlinux password policy"
  become: true
  ansible.builtin.template:
    src: "archlinux-pam-pw.j2"
    dest: "/etc/pam.d/system-auth"
    mode: "0644"
  when: ansible_os_family == "Archlinux"
  # Password policy is technically not required for boot,
  # But it's quite nice to configure it for boot and therefore
  # enforce the required policies/configurations wanted for the first passwrod change
  tags: ["required_for_boot"]

- name: "Configure debian password policy"
  become: true
  ansible.builtin.template:
    src: "debian-pam-pw.j2"
    dest: "/etc/pam.d/common-password"
    mode: "0644"
  when: ansible_os_family == "Debian"
  # Password policy is technically not required for boot,
  # But it's quite nice to configure it for boot and therefore
  # enforce the required policies/configurations wanted for the first passwrod change
  tags: ["required_for_boot"]
