---
- name: "Restart prometheus"
  become: true
  ansible.builtin.systemd_service:
    name: "prometheus"
    state: "restarted"

- name: "Restart node-exporter"
  become: true
  ansible.builtin.systemd_service:
    name: "prometheus-node-exporter"
    state: "restarted"
