---
garage_version: "2.3.0"
garage_capacity: "100G"
garage_data_dir: "/var/garage/data"
garage_meta_dir: "/var/garage/meta"
garage_rpc_secret: "{{ 'changeme' | hash('sha256') }}"
garage_s3_port: "3900"
garage_admin_port: "3903"
garage_rpc_bind_addr: "127.0.0.1:3901"
garage_bucket: "default-bucket"
garage_access_key_id: "{{ ('changeme' | hash('sha256'))[:20] | upper }}"
garage_secret_access_key: "{{ ('changeme' | hash('sha256'))[:40] }}"
