---
- name: "Reload systemd"
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "Restart crond"
  become: true
  ansible.builtin.service:
    name: "crond"
    state: "restarted"
